
LOOP_DELAY: 0.01
ENV_NAME: "DEV"

ENV:
  DEV:
    PORT: 8183
    ENABLE_DB: True
    LOG_SENSOR_DATA: True
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    DB:
      TYPE: "MYSQL"
      HOST: 'localhost'
      USER: 'root'
      PASS: 'safacembani!'
      NAME: 'mqtt_charts_dv'
  PROD:
    PORT: 8083
    ENABLE_DB: True
    LOG_SENSOR_DATA: False
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    DB:
      TYPE: "MYSQL"
      HOST: 'localhost'
      USER: 'root'
      PASS: 'safacembani!'
      NAME: 'mqtt_charts'
  RPI:
    PORT: 8083
    ENABLE_DB: True
    LOG_SENSOR_DATA: False
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    DB:
      TYPE: "POSTGRESQL"
      HOST: '192.168.12.160'
      USER: 'pi'
      PASS: 'raspberry'
      NAME: 'mqtt_charts'

