
LOOP_DELAY: 0.01
# MQTT_BROKER = "192.168.12.160"
MQTT_BROKER: "broker.shiftr.io"
# MQTT_BROKER = "192.168.1.150"
# MQTT_PING_TOPIC = "wsn/check"
MQTT_PING_TOPIC: None
MQTT_SUB_TOPICS: ["wsn/gas/#", "wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
#MQTT_SUB_TOPICS: ["wsn/gas/#"]
ENABLE_DB: True
LOG_SENSOR_DATA: True
DB:
  HOST: '192.168.1.150'
  USER: 'pi'
  PASS: 'raspberry'
  NAME: 'mqtt_charts'



  # self.conn = psycopg2.connect(
  #     host='localhost',
  #     user='pi',
  #     password='raspberry',
  #     dbname='mqtt_charts')
