
LOOP_DELAY: 0.01
ENV_NAME: "DEV"

ENV:
  DEV:
    PORT: 8183
    ENABLE_DB: True
    LOG_SENSOR_DATA: True
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    EXT_API_LOG_INIT: False
    EXT_API:
      - ENDPOINT: "https://airapi.airly.eu/v2/measurements/point"
        ENABLED: True
        PARAMS:
          - KEY: "indexType"
            VALUE: "AIRLY_CAQI"
          - KEY: "lat"
            VALUE: 44.4567471
          - KEY: "lng"
            VALUE: 26.080335
        HEADERS:
          - KEY: "apiKey"
            VALUE: "CSCpT2iBwJvqsAnts1C6dMQc76gIWWXP"
        SENSOR:
          ID: 1
          FULL_ID: 4001
          TYPE: 4
          LOG_RATE: 1800
          NC: 1
          TOPIC: "ext/air/1"
        OUTPUT:
          - KEY: ["current", "indexes", 0, "value"]
      - ENDPOINT: "http://api.waqi.info/feed/bucharest/"
        ENABLED: True
        PARAMS:
          - KEY: "token"
            VALUE: "66d9a11121d73df5702af7579cf8c11a62d52f50"
          - KEY: "city"
            VALUE: "bucharest"
        SENSOR:
          ID: 2
          FULL_ID: 4002
          TYPE: 4
          LOG_RATE: 1800
          NC: 1
          TOPIC: "ext/air/1"
        OUTPUT:
          - KEY: ["data", "aqi"]
      - ENDPOINT: "http://api.airvisual.com/v2/nearest_city"
        ENABLED: True
        PARAMS:
          - KEY: "key"
            VALUE: "kFHKw8oi3K56wzRhN"
          - KEY: "lat"
            VALUE: 44.435051
          - KEY: "lon"
            VALUE: 26.0473631
        SENSOR:
          ID: 1
          FULL_ID: 3001
          TYPE: 3
          LOG_RATE: 1800
          NC: 2
          TOPIC: "ext/air/2"
        OUTPUT:
          - KEY: ["data", "current", "pollution", "aqius"]
        DERIVATE:
          - SRC: 0
            DEST: 1
            GTZ: True
            FLOOR: True
            LIN: [0.6613, -10.07]
    DB:
      TYPE: "MYSQL"
      # HOST: 'localhost'
      # USER: 'root'
      # PASS: 'safacembani!'
      # NAME: 'mqtt_charts_dv'
      HOST: '192.168.1.150'
      USER: 'pi'
      PASS: 'raspberry'
      NAME: 'mqtt_charts'
  PROD:
    PORT: 8083
    ENABLE_DB: True
    LOG_SENSOR_DATA: False
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    EXT_API_LOG_INIT: False
    EXT_API:
      - ENDPOINT: "https://airapi.airly.eu/v2/measurements/point"
        ENABLED: True
        PARAMS:
          - KEY: "indexType"
            VALUE: "AIRLY_CAQI"
          - KEY: "lat"
            VALUE: 44.435051
          - KEY: "lng"
            VALUE: 26.0473631
        HEADERS:
          - KEY: "apiKey"
            VALUE: "CSCpT2iBwJvqsAnts1C6dMQc76gIWWXP"
        SENSOR:
          ID: 1
          FULL_ID: 4001
          TYPE: 4
          LOG_RATE: 3600
          NC: 1
          TOPIC: "ext/air/1"
        OUTPUT:
          - KEY: ["current", "indexes", 0, "value"]
      - ENDPOINT: "http://api.waqi.info/feed/bucharest/"
        ENABLED: True
        PARAMS:
          - KEY: "token"
            VALUE: "66d9a11121d73df5702af7579cf8c11a62d52f50"
          - KEY: "city"
            VALUE: "bucharest"
        SENSOR:
          ID: 2
          FULL_ID: 4002
          TYPE: 4
          LOG_RATE: 3600
          NC: 1
          TOPIC: "ext/air/1"
        OUTPUT:
          - KEY: ["data", "aqi"]
      - ENDPOINT: "http://api.airvisual.com/v2/nearest_city"
        ENABLED: True
        PARAMS:
          - KEY: "key"
            VALUE: "kFHKw8oi3K56wzRhN"
          - KEY: "lat"
            VALUE: 44.435051
          - KEY: "lon"
            VALUE: 26.0473631
        SENSOR:
          ID: 1
          FULL_ID: 3001
          TYPE: 3
          LOG_RATE: 3600
          NC: 2
          TOPIC: "ext/air/2"
        OUTPUT:
          - KEY: ["data", "current", "pollution", "aqius"]
        DERIVATE:
          - SRC: 0
            DEST: 1
            GTZ: True
            FLOOR: True
            LIN: [0.6613, -10.07]
    DB:
      TYPE: "MYSQL"
      HOST: 'localhost'
      USER: 'root'
      PASS: 'safacembani!'
      NAME: 'mqtt_charts'
  RPI:
    PORT: 8083
    ENABLE_DB: True
    LOG_SENSOR_DATA: False
    MQTT_BROKER: "broker.shiftr.io"
    MQTT_PING_TOPIC: None
    MQTT_SUB_TOPICS: ["wsn/indoor_ws/#", "wsn/outdoor_ws/#"]
    DB:
      TYPE: "POSTGRESQL"
      HOST: '192.168.12.160'
      USER: 'pi'
      PASS: 'raspberry'
      NAME: 'mqtt_charts'

